### ISSUE TITLE
Hacktoberfest at Aqua Security

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/community#1]
Dear community, we appreciate you and your contribution to the success of our open source projects! In celebration of [Hacktoberfest](https://hacktoberfest.digitalocean.com/), we would like to extend our appreciation and reward your hard work. This repository is participating in Aqua Security 2020 Hacktoberfest campaign. For full details and guidelines please visit the official repo: [Hacktoberfest at Aqua Security](https://github.com/aquasecurity/Hacktoberfest).

**Comment by AnaisUrlichs** [comment]
Closing this issue as it's nearly three years since Hacktoberfest took place and we now have Aqua Stars
