### ISSUE TITLE
Simple Kubernetes vulnerability scanner based on Trivy

### ISSUE THREAD

**Issue by smbikina** [aquasecurity/community#36]
Does an issue related to this integration already exists in the project's repository? If so, please reuse the existing issue.

Is this integration generally valuable to the project and should be discussed in the project's repository? If so, please open the issue in the project's repository instead.

Please describe the integration you propose:
A simple tool named kubevscan which scans Kubernetes cluster's containers for vulnerabilities using Trivy. 

What are you integrating with?

Please a link to the other party's repository or website:

Where are you going to implement this integration? please provide a link to the place where the code will reside (if this is going to be a PR to an Aqua project, then please open this issue there instead):
https://github.com/nonstandardlogic/kubevscan

**Comment by itaysk** [comment]
LGTM, thanks! Please open a PR to contrib-integrations.md with this info so that we can recognize it for hacktoberfest

**Comment by smbikina** [comment]
Thanks!  PR created https://github.com/aquasecurity/Hacktoberfest/pull/41

**Comment by AnaisUrlichs** [comment]
Closing this issue, thank you for your contributions :)
